figure(1);
dplot = reshape(dprime_xy,size(dprime_xy,2),size(dprime_xy,3));
plot(MeshX(1,:),dplot(:,:),'LineWidth',2), xlabel('Future total wealth x^{\prime}','Fontsize',12), ylabel('Future durable wealth d^{\prime}','Fontsize',12);
xlim([-1 max(x_grid_)])
ylim([min(min(dplot)) max(max(dplot))])
text(0.1,4.5,'\leftarrow Collateral constraint',...
     'HorizontalAlignment','left','Fontsize',12);
text(15,1.3,'Non-negative durable-stock constraint',...
     'HorizontalAlignment','left','Fontsize',12);
text(23,0.3,'\downarrow',...
     'HorizontalAlignment','left');
text(0.5,14.5,'Unconstrained locus in highest income state',...
     'HorizontalAlignment','left','Fontsize',12);
text(37,13.5,'\downarrow',...
     'HorizontalAlignment','left');
text(18,3.5,'Unconstrained locus in lowest income state',...
     'HorizontalAlignment','left','Fontsize',12);
text(27,4.5,'\uparrow',...
     'HorizontalAlignment','left','Fontsize',12);
%saveas(1,[DISC_PATH case_id_out 'fig1.eps'],'psc2');